In [1]:
import numpy as np

In [5]:
!pip install numpy

In [7]:
arr = np.array([1,3,6])
arr

array([1, 3, 6])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [27]:
np.linspace(1,100,5) #equally spaced arrays

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [29]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [31]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [33]:
myarr.shape

(4, 3)

In [35]:
myarr.size

12

In [37]:
myarr.ndim

2

In [41]:
myarr.dtype #strongly types

dtype('int32')

In [43]:
myarr.astype('float64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [45]:
n=myarr.astype('float64')

In [47]:
n.dtype

dtype('float64')

In [49]:
myarr.dtype

dtype('int32')

In [51]:
myarr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32')

In [53]:
myarr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [55]:
myarr1.dtype

dtype('float32')

In [57]:
myarr.shape

(4, 3)

In [61]:
reshaped = myarr.reshape(3,4) #reshape arrays

In [63]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [65]:
myarr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [69]:
#flatten
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])